# theme: one-dark-float
background              #282C34
foreground              #ABB2BF
cursor                  #ABB2BF
cursor_text_color       #282C34
selection_foreground    #ABB2BF
selection_background    #3E4451
active_tab_background   #2C313A
active_tab_foreground   #61AFEF
inactive_tab_background #21252B
inactive_tab_foreground #5C6370

background_opacity 0.90
