background = 0xFF282C34
base = 0xFF2C313A
text = 0xFFABB2BF
alternate_base = 0xFF21252B
bright_text = 0xFF61AFEF
accent = 0xFF61AFEF
link_text = 0xFF61AFEF
accent_secondary = 0xFF5C6370
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 8
rounding_small = 4
